name: Deploy to S3

on:
  push:
    branches: [main]

env:
  AWS_REGION: 'eu-west-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MINIFY: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main

      - name: Deploy Infra
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: thesheps-dev
          template: website.yml

      - name: Deploy site
        uses: plopcas/hugo-s3-action@v1.3.0