name: Deploy to S3

on:
  push:
    branches: [main]

env:
  AWS_REGION: 'eu-west-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@main
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy Infra
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: thesheps-dev
          template: website.yml
          no-fail-on-empty-changeset: "1"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.1'

      - name: Build Site
        run: hugo --log --verbose

      - name: Deploy Site
        run: hugo deploy